version: "3.8"
services:
  web:
    build: ./web
    ports:
      - 10000:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - appfront
  appfront:
    build: ./application/front
    volumes:
      - ./application/front:/home/app/financialStatement
      - ./application/front/node_modules:/home/app/financialStatement/node_modules
