my_first_job:
  cron: "*/20 * * * * *"
  class: SandboxTask
  queue: default
  args:
    name: "stuffA"
    count: 103
my_second_job:
  cron: "*/2 * * * *"
  class: SandboxTask
  queue: default
  args:
    name: "stuffB"
    count: 105
